### ISSUE TITLE
Terminal requirements?

### ISSUE THREAD

**Issue by sirolf2009** [p-gen/smenu#16]
I'm building my own terminal in java (https://github.com/sirolf2009/javafx-terminal) and when I try to run smenu I get the error "The terminal does not have the required cursor management capabilities". Can you point me to what those capabilities are so that I can add support to my terminal?

**Comment by p-gen** [comment]
To work properly, smenu requires basic _terminfo_ capabilities, namely `cuu1`, `cud1`, `cub1`, `cuf1`, `sc` and `rc`. For this, it tries to identify the terminal using the `TERM` environment variable in order to extract their values ​​from the _terminfo_ database.

You can try forcing a known terminal by setting the `TERM` variable to `xterm` for example before running smenu.

**Comment by sirolf2009** [comment]
That makes sense, cheers
