### ISSUE TITLE
Precompiled binaries

### ISSUE THREAD

**Issue by rockandska** [p-gen/smenu#22]
Hi,

Would be nice to have pre-compiled binaries for different architecture to let user test/use smenu quickly without the need to compile it.

Regards,

**Comment by p-gen** [comment]
Hi,

Here are some places where you can find binary packages: https://software.opensuse.org/download.html?project=home%3Apgen&package=smenu
https://repology.org/project/smenu/versions

Regards.

**Comment by rockandska** [comment]
Thanks.

Not possible to have them as artifact on GH by architecture (darwin,linux_x86,etc..) and not by distribution ? 

Regards,

**Comment by p-gen** [comment]
It's not planned. I think that to share code, open-source is the way.
After all, smenu is not that difficult to compile.

**Comment by NightMachinary** [comment]
@p-gen It's not difficult, but it uses up time nonetheless. And one needs to spend this time for each new OS installation. Having `smenu` packaged in the popular package managers (I particularly like `brew` because it works on both macOS and Linux; `nix` is another such option with a lot of overhead.) allows people to simply add it to their "bootstrap" script for getting new machines up to speed.

**Comment by p-gen** [comment]
For convenience, release 0.9.16 has precompiled static binaries attached for 64-bit Linux and FreeBSD.
