### ISSUE TITLE
-g|-gutter missing in -h output

### ISSUE THREAD

**Issue by mcstafford-git** [p-gen/smenu#38]
Expected:

Some of the gutter text from [master/usage.c](https://github.com/p-gen/smenu/blob/master/ctxopt.c)

Actual:

```
$ smenu --version
Version: 1.1.0

$  smenu -h | grep -E '\-g|\-gutter'
  [-z|-zap|-zap-glyphs #bytes] [-n|-lines|-height [#height]] [-b|-blank] 
  [-f|-forgotten_timeout|-global_timeout #timeout] 
-f|-forgotten_timeout|-global_timeout
```

Same result from v1.1.0 glibc static release, and binary built using build.sh as of 4068e3a.

**Comment by p-gen** [comment]
Hi, I'll make it clearer in the manual but as `-g|-gutter` is only defined in Columns and Tabulations modes you have to enter either:
- `smenu -c -h | grep -E '\-g\|\-gutter'` (Columns mode)
- `smenu -t -h | grep -E '\-g\|\-gutter'` (Tabilations mode)
- `smenu -H | grep -E '\-g\|\-gutter'` (long help)

You also need to prepend either `-c` or `-t` before being able to user `-g` to be able to set guters as in `smenu -c -g` per example.

`smenu -g` displays an error message saying this at its very beginning, but again I should find a way to make it clearer.

The reason is that the use of `-g` does not make sense when the words are not vertically aligned.
